START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021041746_AddChatContextTables') THEN
    CREATE TABLE "ChatSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid,
        "BookstoreId" integer,
        "CreatedAt" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "LastActive" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ChatSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021041746_AddChatContextTables') THEN
    CREATE TABLE "ChatMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SessionId" integer NOT NULL,
        "Sender" character varying(50) NOT NULL,
        "Content" text NOT NULL,
        "Timestamp" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatMessages_ChatSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "ChatSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021041746_AddChatContextTables') THEN
    CREATE INDEX "IX_ChatMessages_SessionId" ON "ChatMessages" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021041746_AddChatContextTables') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021041746_AddChatContextTables', '8.0.17');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021043021_AddChatEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021043021_AddChatEntities', '8.0.17');
    END IF;
END $EF$;
COMMIT;

